# Generated by Django 5.0.6 on 2024-05-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_answer_answer_text_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='option_a',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_d',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
    ]
