# Generated by Django 5.0.6 on 2024-05-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_option_a_questionoption_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_option',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default=None, max_length=200, null=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.option'),
            preserve_default=False,
        ),
    ]
